import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "./globals.css";
import AppThemeProvider from "@/context/MuiThemeContext";
import InitColorSchemeScript from '@mui/material/InitColorSchemeScript';
import { MainAppBar } from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <AppRouterCacheProvider options={{enableCssLayer: false}}>
          <AppThemeProvider>
          {/* <InitColorSchemeScript attribute="class" defaultMode="system" /> */}
          <InitColorSchemeScript attribute="class" />
          <MainAppBar />
          {children}
          </AppThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
